branches:
  only:
    - master
language: node_js
node_js:
  - "node"
  - "12"
sudo: false
scripts:
  - npm install typescript -g
  - npm install codecov -g
  - npm run test
after_success:
  - codecov
